exports.CURRENCIES = [
  { value: 'EUR', label: 'EUR - Euro' },
  { value: 'GBP', label: 'GBP - British Pound' },
  { value: 'USD', label: 'USD - United States dollar' },
  { value: 'AUD', label: 'AUD - Australian dollar' },
  { value: 'BGN', label: 'BGN - Bulgarian Iev' },
  { value: 'BRL', label: 'BRL - Brazilian real' },
  { value: 'CAD', label: 'CAD - Canadian dollar' },
  { value: 'CHF', label: 'CHF - Swiss franc' },
  { value: 'CZK', label: 'CZK - Czech koruna' },
  { value: 'DKK', label: 'DKK - Danish krone' },
  { value: 'HKD', label: 'HKD - Honk Kong dollar' },
  { value: 'HRK', label: 'HRK - Croation kuna' },
  { value: 'HUF', label: 'HUF - Hungarian forint' },
  { value: 'JPY', label: 'JPY - Japanese yen' },
  { value: 'NOK', label: 'NOK - Norvegian krone' },
  { value: 'NZD', label: 'NZD - New Zealand dollar' },
  { value: 'PLN', label: 'PLN - Polish złoty' },
  { value: 'RON', label: 'RON - Romanian leu' },
  { value: 'SEK', label: 'SEK - Swedish krona' },
  { value: 'SGD', label: 'SGD - Singapore dollar' },
  { value: 'TRY', label: 'TRY - Turkish lira' }
]
